name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      if: github.event_name == 'pull_request'
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: actions/checkout@v4
      if: github.event_name == 'push'
      with:
        fetch-depth: 0

    - name: autoreconf
      run: autoreconf --install

    - name: Enter build
      run: cd build

    - name: configure
      run: ../configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
